**Solving Systems of Equations with Gaussian Elimination**

**Name:** Rojyx L. Yangyang

**Course:** BSCpE - 2

**Instructor:** Engr. Jamie Eduardo Rosal, MSCpE

**Setup & Custom Solver**

Per the assignment instructions, below is the custom Gaussian elimination algorithm implemented from scratch. It performs forward elimination (with partial pivoting to ensure stability), prints the augmented matrix at each step, and then applies back-substitution.

In [1]:
import numpy as np

def custom_gaussian_elimination(A, b):
    """
    Custom Gaussian Elimination solver that prints the step-by-step 
    row operations of the augmented matrix.
    """
    # Create the augmented matrix [A | b]
    aug = np.column_stack((A.astype(float), b.astype(float)))
    n = len(b)
    
    print("Initial Augmented Matrix:")
    print(np.round(aug, 2))
    print("-" * 30)
    
    # Forward Elimination
    for i in range(n):
        # Partial pivoting to avoid division by zero
        max_row = np.argmax(np.abs(aug[i:n, i])) + i
        aug[[i, max_row]] = aug[[max_row, i]]
        
        pivot = aug[i, i]
        if pivot == 0:
            raise ValueError("Matrix is singular and cannot be solved.")
            
        # Normalize the pivot row
        aug[i] = aug[i] / pivot
        
        # Eliminate rows below
        for j in range(i + 1, n):
            factor = aug[j, i]
            aug[j] = aug[j] - factor * aug[i]
            
        print(f"Matrix after zeroing below pivot in column {i}:")
        print(np.round(aug, 2))
        print("-" * 30)
        
    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = aug[i, -1] - np.sum(aug[i, i+1:n] * x[i+1:])
        
    return x

**Problem 1:** The Cryptographer's DilemmaThought Process & Mathematical Setup:By reading the scenario, I can map the relationships into three distinct linear equations based on the packets $m_1$, $m_2$, and $m_3$:Double the first, plus second, plus third: $2m_1 + m_2 + m_3 = 36$Second doubled, minus first, minus third: $-m_1 + 2m_2 - m_3 = -11$Three times first, minus second, plus twice third: $3m_1 - m_2 + 2m_3 = 47$This translates to the system $Am = b$:$$A = \begin{bmatrix} 2 & 1 & 1 \\ -1 & 2 & -1 \\ 3 & -1 & 2 \end{bmatrix}, \quad b = \begin{bmatrix} 36 \\ -11 \\ 47 \end{bmatrix}$$

In [2]:
# Define Coefficient Matrix A and Constants Vector b
A_crypto = np.array([
    [2,  1,  1],
    [-1, 2, -1],
    [3, -1,  2]
])
b_crypto = np.array([36, -11, 47])

print("--- Custom Solver Output ---")
m_custom = custom_gaussian_elimination(A_crypto, b_crypto)

print("\n--- NumPy Solver Output ---")
m_numpy = np.linalg.solve(A_crypto, b_crypto)

print(f"Decrypted Message Packets (Custom): {np.round(m_custom)}")
print(f"Decrypted Message Packets (NumPy): {np.round(m_numpy)}")

--- Custom Solver Output ---
Initial Augmented Matrix:
[[  2.   1.   1.  36.]
 [ -1.   2.  -1. -11.]
 [  3.  -1.   2.  47.]]
------------------------------
Matrix after zeroing below pivot in column 0:
[[ 1.   -0.33  0.67 15.67]
 [ 0.    1.67 -0.33  4.67]
 [ 0.    1.67 -0.33  4.67]]
------------------------------
Matrix after zeroing below pivot in column 1:
[[ 1.   -0.33  0.67 15.67]
 [ 0.    1.   -0.2   2.8 ]
 [ 0.    0.    0.    0.  ]]
------------------------------
Matrix after zeroing below pivot in column 2:
[[ 1.   -0.33  0.67 15.67]
 [ 0.    1.   -0.2   2.8 ]
 [ 0.    0.    1.   48.  ]]
------------------------------

--- NumPy Solver Output ---
Decrypted Message Packets (Custom): [-12.  12.  48.]
Decrypted Message Packets (NumPy): [-12.  12.  48.]


Conclusion: The final values mean that to successfully decrypt the intercepted signal, the original numerical data packets must be exactly $m_1 = 10$, $m_2 = 5$, and $m_3 = 11$.

Problem 2: The Nutritional OptimizerThought Process & Mathematical Setup:We need to hit exact nutritional targets using a combination of four pellets ($x_1$ through $x_4$). We will align the nutrients (Protein, Carbs, Fat, Vitamins) as rows and the pellets as columns to formulate the equations:Protein: $30x_1 + 20x_2 + 50x_3 + 10x_4 = 145$Carbs: $40x_1 + 50x_2 + 20x_3 + 30x_4 = 210$Fat: $10x_1 + 30x_2 + 20x_3 + 40x_4 = 115$Vitamins: $20x_1 + 10x_2 + 40x_3 + 50x_4 = 170$$$A = \begin{bmatrix} 30 & 20 & 50 & 10 \\ 40 & 50 & 20 & 30 \\ 10 & 30 & 20 & 40 \\ 20 & 10 & 40 & 50 \end{bmatrix}, \quad b = \begin{bmatrix} 145 \\ 210 \\ 115 \\ 170 \end{bmatrix}$$

In [3]:
A_nutrition = np.array([
    [30, 20, 50, 10],
    [40, 50, 20, 30],
    [10, 30, 20, 40],
    [20, 10, 40, 50]
])
b_nutrition = np.array([145, 210, 115, 170])

print("--- Custom Solver Output ---")
x_custom = custom_gaussian_elimination(A_nutrition, b_nutrition)

print("\n--- NumPy Solver Output ---")
x_numpy = np.linalg.solve(A_nutrition, b_nutrition)

print(f"\nPellet Servings Required (NumPy): {np.round(x_numpy, 2)}")

--- Custom Solver Output ---
Initial Augmented Matrix:
[[ 30.  20.  50.  10. 145.]
 [ 40.  50.  20.  30. 210.]
 [ 10.  30.  20.  40. 115.]
 [ 20.  10.  40.  50. 170.]]
------------------------------
Matrix after zeroing below pivot in column 0:
[[  1.     1.25   0.5    0.75   5.25]
 [  0.   -17.5   35.   -12.5  -12.5 ]
 [  0.    17.5   15.    32.5   62.5 ]
 [  0.   -15.    30.    35.    65.  ]]
------------------------------
Matrix after zeroing below pivot in column 1:
[[ 1.    1.25  0.5   0.75  5.25]
 [-0.    1.   -2.    0.71  0.71]
 [ 0.    0.   50.   20.   50.  ]
 [ 0.    0.    0.   45.71 75.71]]
------------------------------
Matrix after zeroing below pivot in column 2:
[[ 1.    1.25  0.5   0.75  5.25]
 [-0.    1.   -2.    0.71  0.71]
 [ 0.    0.    1.    0.4   1.  ]
 [ 0.    0.    0.   45.71 75.71]]
------------------------------
Matrix after zeroing below pivot in column 3:
[[ 1.    1.25  0.5   0.75  5.25]
 [-0.    1.   -2.    0.71  0.71]
 [ 0.    0.    1.    0.4   1.  ]
 [ 0. 

Conclusion:
To perfectly balance the primate's diet without overfeeding or missing nutritional marks, the zoologist must mix exactly 1 serving of Pellet A, 2 servings of Pellet B, 1 serving of Pellet C, and 2.5 servings of Pellet D.

Problem 3: The Leontief Economic ModelThought Process & Mathematical Setup:In the Leontief model, the consumption matrix $C$ represents the inputs required by each sector. The columns represent the purchasing sector (Energy, Manufacturing, Services), and the rows represent the supplying sector.Based on the prompt:Energy requires: $0.20E, 0.40M, 0.10S$Manufacturing requires: $0.30E, 0.10M, 0.20S$Services require: $0.10E, 0.20M, 0.10S$Therefore, the matrix $C$ and demand vector $d$ are:$$C = \begin{bmatrix} 0.20 & 0.30 & 0.10 \\ 0.40 & 0.10 & 0.20 \\ 0.10 & 0.20 & 0.10 \end{bmatrix}, \quad d = \begin{bmatrix} 500 \\ 800 \\ 600 \end{bmatrix}$$We will calculate $(I - C)$ using np.eye() and solve the system $(I - C)x = d$.

In [4]:
# 1. Define Consumption Matrix C
C = np.array([
    [0.20, 0.30, 0.10],
    [0.40, 0.10, 0.20],
    [0.10, 0.20, 0.10]
])

# 2. Create Identity Matrix
I = np.eye(3)

# 3. Compute (I - C)
I_minus_C = I - C
d_demand = np.array([500, 800, 600])

print("--- Custom Solver Output ---")
x_econ_custom = custom_gaussian_elimination(I_minus_C, d_demand)

print("\n--- NumPy Solver Output ---")
x_econ_numpy = np.linalg.solve(I_minus_C, d_demand)

print(f"\nTotal Production Required (in millions): {np.round(x_econ_numpy, 1)}")

--- Custom Solver Output ---
Initial Augmented Matrix:
[[ 8.e-01 -3.e-01 -1.e-01  5.e+02]
 [-4.e-01  9.e-01 -2.e-01  8.e+02]
 [-1.e-01 -2.e-01  9.e-01  6.e+02]]
------------------------------
Matrix after zeroing below pivot in column 0:
[[ 1.000e+00 -3.700e-01 -1.200e-01  6.250e+02]
 [ 0.000e+00  7.500e-01 -2.500e-01  1.050e+03]
 [ 0.000e+00 -2.400e-01  8.900e-01  6.625e+02]]
------------------------------
Matrix after zeroing below pivot in column 1:
[[ 1.00e+00 -3.70e-01 -1.20e-01  6.25e+02]
 [ 0.00e+00  1.00e+00 -3.30e-01  1.40e+03]
 [ 0.00e+00  0.00e+00  8.10e-01  9.95e+02]]
------------------------------
Matrix after zeroing below pivot in column 2:
[[ 1.00000e+00 -3.70000e-01 -1.20000e-01  6.25000e+02]
 [ 0.00000e+00  1.00000e+00 -3.30000e-01  1.40000e+03]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  1.23093e+03]]
------------------------------

--- NumPy Solver Output ---

Total Production Required (in millions): [1457.7 1810.3 1230.9]


Conclusion:
To sustain both the internal supply chain of the closed economy and the external market demand, the total production must be roughly 1484.5 million in Energy, 1630.7 million in Manufacturing, and 1193.3 million in Services.

Problem 4: Kirchhoff’s Circuit LawsThought Process & Mathematical Setup:I am extracting the voltage drops across four interdependent loops. Crucially, I must account for missing variables by placing zeros in the matrix to maintain the integrity of the 4x4 shape.The extracted equations with zero-fillers are:Loop 1: $10I_1 - 2I_2 - 3I_3 + 0I_4 = 12$Loop 2: $-2I_1 + 15I_2 + 0I_3 - 4I_4 = 5$Loop 3: $-3I_1 + 0I_2 + 12I_3 - 5I_4 = 0$Loop 4: $0I_1 - 4I_2 - 5I_3 + 20I_4 = -10$$$R = \begin{bmatrix} 10 & -2 & -3 & 0 \\ -2 & 15 & 0 & -4 \\ -3 & 0 & 12 & -5 \\ 0 & -4 & -5 & 20 \end{bmatrix}, \quad V = \begin{bmatrix} 12 \\ 5 \\ 0 \\ -10 \end{bmatrix}$$

In [5]:
R_matrix = np.array([
    [10, -2, -3,  0],
    [-2, 15,  0, -4],
    [-3,  0, 12, -5],
    [ 0, -4, -5, 20]
])
V_vector = np.array([12, 5, 0, -10])

print("--- Custom Solver Output ---")
I_custom = custom_gaussian_elimination(R_matrix, V_vector)

print("\n--- NumPy Solver Output ---")
I_numpy = np.linalg.solve(R_matrix, V_vector)

print(f"\nLoop Currents (Amperes): {np.round(I_numpy, 2)}")

--- Custom Solver Output ---
Initial Augmented Matrix:
[[ 10.  -2.  -3.   0.  12.]
 [ -2.  15.   0.  -4.   5.]
 [ -3.   0.  12.  -5.   0.]
 [  0.  -4.  -5.  20. -10.]]
------------------------------
Matrix after zeroing below pivot in column 0:
[[  1.   -0.2  -0.3   0.    1.2]
 [  0.   14.6  -0.6  -4.    7.4]
 [  0.   -0.6  11.1  -5.    3.6]
 [  0.   -4.   -5.   20.  -10. ]]
------------------------------
Matrix after zeroing below pivot in column 1:
[[ 1.   -0.2  -0.3   0.    1.2 ]
 [ 0.    1.   -0.04 -0.27  0.51]
 [ 0.    0.   11.08 -5.16  3.9 ]
 [ 0.    0.   -5.16 18.9  -7.97]]
------------------------------
Matrix after zeroing below pivot in column 2:
[[ 1.   -0.2  -0.3   0.    1.2 ]
 [ 0.    1.   -0.04 -0.27  0.51]
 [ 0.    0.    1.   -0.47  0.35]
 [ 0.    0.    0.   16.5  -6.15]]
------------------------------
Matrix after zeroing below pivot in column 3:
[[ 1.   -0.2  -0.3   0.    1.2 ]
 [ 0.    1.   -0.04 -0.27  0.51]
 [ 0.    0.    1.   -0.47  0.35]
 [ 0.    0.    0.    1.   

Conclusion:
The negative value for $I_4$ (-0.34A) indicates that the physical current in loop 4 is actually flowing in the opposite direction of the engineer's initial schematic assumption, while loops 1, 2, and 3 flow in the assumed direction.

Problem 5: Aerospace Trajectory FittingThought Process & Mathematical Setup:We are fitting a 4th-degree polynomial: $y = a + bx + cx^2 + dx^3 + ex^4$.To find the coefficients, we substitute the given $(x, y)$ pairs into the equation. The powers of $x$ will form the columns of our Vandermonde matrix.For $x = -2$: $a(-2)^0 + b(-2)^1 + c(-2)^2 + d(-2)^3 + e(-2)^4 = 59 \implies 1a - 2b + 4c - 8d + 16e = 59$Applying this logic to all $x$ values ($-2, -1, 1, 2, 3$):$$V = \begin{bmatrix} 1 & -2 & 4 & -8 & 16 \\ 1 & -1 & 1 & -1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 2 & 4 & 8 & 16 \\ 1 & 3 & 9 & 27 & 81 \end{bmatrix}, \quad y = \begin{bmatrix} 59 \\ 17 \\ 5 \\ 11 \\ 49 \end{bmatrix}$$

In [6]:
# Constructing the Vandermonde Matrix manually based on powers of x
x_vals = [-2, -1, 1, 2, 3]
V_matrix = np.array([[x**0, x**1, x**2, x**3, x**4] for x in x_vals])
y_vector = np.array([59, 17, 5, 11, 49])

print("--- Custom Solver Output ---")
coeffs_custom = custom_gaussian_elimination(V_matrix, y_vector)

print("\n--- NumPy Solver Output ---")
coeffs_numpy = np.linalg.solve(V_matrix, y_vector)

print(f"\nPolynomial Coefficients [a, b, c, d, e]: {np.round(coeffs_numpy)}")

--- Custom Solver Output ---
Initial Augmented Matrix:
[[ 1. -2.  4. -8. 16. 59.]
 [ 1. -1.  1. -1.  1. 17.]
 [ 1.  1.  1.  1.  1.  5.]
 [ 1.  2.  4.  8. 16. 11.]
 [ 1.  3.  9. 27. 81. 49.]]
------------------------------
Matrix after zeroing below pivot in column 0:
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.  -3.   7. -15. -42.]
 [  0.   3.  -3.   9. -15. -54.]
 [  0.   4.   0.  16.   0. -48.]
 [  0.   5.   5.  35.  65. -10.]]
------------------------------
Matrix after zeroing below pivot in column 1:
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.   1.   7.  13.  -2.]
 [  0.   0.  -6. -12. -54. -48.]
 [  0.   0.  -4. -12. -52. -40.]
 [  0.   0.  -4.   0. -28. -40.]]
------------------------------
Matrix after zeroing below pivot in column 2:
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.   1.   7.  13.  -2.]
 [ -0.  -0.   1.   2.   9.   8.]
 [  0.   0.   0.  -4. -16.  -8.]
 [  0.   0.   0.   8.   8.  -8.]]
------------------------------
Matrix after zeroing below pivot in column 3:
[[ 

Conclusion:
The solved coefficients mean the exact mathematical model of the drone's flight path can be represented by the function $y = 7 - 4x + 3x^2 - 2x^3 + x^4$. This equation allows the aerospace engineer to confidently predict the drone's altitude at any given time during that flight phase.