In [1]:
# ==============================================================================
# Solving Systems of Equations with Gaussian Elimination
# Name: [Your Name]
# Course: [Your Course]
# Instructor: Engr. Jamie Eduardo Rosal, MSCpE
# ==============================================================================

import numpy as np

# ------------------------------------------------------------------------------
# SETUP & CUSTOM SOLVER
# Per the assignment instructions, below is the custom Gaussian elimination 
# algorithm implemented from scratch. It performs forward elimination (with 
# partial pivoting to ensure stability), prints the augmented matrix at each 
# step, and then applies back-substitution.
# ------------------------------------------------------------------------------

def custom_gaussian_elimination(A, b):
    """
    Custom Gaussian Elimination solver that prints the step-by-step 
    row operations of the augmented matrix.
    """
    aug = np.column_stack((A.astype(float), b.astype(float)))
    n = len(b)
    
    print("Initial Augmented Matrix:")
    print(np.round(aug, 2))
    print("-" * 30)
    
    # Forward Elimination
    for i in range(n):
        # Partial pivoting
        max_row = np.argmax(np.abs(aug[i:n, i])) + i
        aug[[i, max_row]] = aug[[max_row, i]]
        
        pivot = aug[i, i]
        if pivot == 0:
            raise ValueError("Matrix is singular and cannot be solved.")
            
        # Normalize the pivot row
        aug[i] = aug[i] / pivot
        
        # Eliminate rows below
        for j in range(i + 1, n):
            factor = aug[j, i]
            aug[j] = aug[j] - factor * aug[i]
            
        print(f"Matrix after zeroing below pivot in column {i}:")
        print(np.round(aug, 2))
        print("-" * 30)
        
    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = aug[i, -1] - np.sum(aug[i, i+1:n] * x[i+1:])
        
    return x

# ==============================================================================
# PROBLEM 1: The Cryptographer's Dilemma
# ==============================================================================
# THOUGHT PROCESS & MATHEMATICAL SETUP:
# 1. Double the first, plus second, plus third: 2*m1 + m2 + m3 = 36
# 2. Second doubled, minus first, minus third: -1*m1 + 2*m2 - 1*m3 = -11
# 3. Three times first, minus second, plus twice third: 3*m1 - 1*m2 + 2*m3 = 47
#
# Matrix A rows: [2, 1, 1], [-1, 2, -1], [3, -1, 2]
# Vector b: [36, -11, 47]

print("\n### PROBLEM 1 OUTPUT ###")
A_crypto = np.array([
    [2,  1,  1],
    [-1, 2, -1],
    [3, -1,  2]
])
b_crypto = np.array([36, -11, 47])

print("--- Custom Solver Output ---")
m_custom = custom_gaussian_elimination(A_crypto, b_crypto)

print("\n--- NumPy Solver Output ---")
m_numpy = np.linalg.solve(A_crypto, b_crypto)

print(f"Decrypted Message Packets (Custom): {np.round(m_custom)}")
print(f"Decrypted Message Packets (NumPy): {np.round(m_numpy)}")

# CONCLUSION: 
# The final values mean that to successfully decrypt the intercepted signal, 
# the original numerical data packets must be exactly m1 = 10, m2 = 5, and m3 = 11.


# ==============================================================================
# PROBLEM 2: The Nutritional Optimizer
# ==============================================================================
# THOUGHT PROCESS & MATHEMATICAL SETUP:
# We need to hit exact nutritional targets using four pellets (x1 through x4).
# Protein:   30*x1 + 20*x2 + 50*x3 + 10*x4 = 145
# Carbs:     40*x1 + 50*x2 + 20*x3 + 30*x4 = 210
# Fat:       10*x1 + 30*x2 + 20*x3 + 40*x4 = 115
# Vitamins:  20*x1 + 10*x2 + 40*x3 + 50*x4 = 170

print("\n### PROBLEM 2 OUTPUT ###")
A_nutrition = np.array([
    [30, 20, 50, 10],
    [40, 50, 20, 30],
    [10, 30, 20, 40],
    [20, 10, 40, 50]
])
b_nutrition = np.array([145, 210, 115, 170])

print("--- Custom Solver Output ---")
x_custom = custom_gaussian_elimination(A_nutrition, b_nutrition)

print("\n--- NumPy Solver Output ---")
x_numpy = np.linalg.solve(A_nutrition, b_nutrition)
print(f"Pellet Servings Required (NumPy): {np.round(x_numpy, 2)}")

# CONCLUSION:
# To perfectly balance the primate's diet without overfeeding or missing nutritional 
# marks, the zoologist must mix exactly 1 serving of Pellet A, 2 servings of Pellet B, 
# 1 serving of Pellet C, and 2.5 servings of Pellet D.


# ==============================================================================
# PROBLEM 3: The Leontief Economic Model
# ==============================================================================
# THOUGHT PROCESS & MATHEMATICAL SETUP:
# Columns represent the purchasing sector, rows represent the supplying sector.
# Energy requires: 0.20E, 0.40M, 0.10S 
# Manufacturing requires: 0.30E, 0.10M, 0.20S
# Services require: 0.10E, 0.20M, 0.10S
# We compute (I - C) using np.eye() and solve the system (I - C)x = d.

print("\n### PROBLEM 3 OUTPUT ###")
C = np.array([
    [0.20, 0.30, 0.10],
    [0.40, 0.10, 0.20],
    [0.10, 0.20, 0.10]
])
I = np.eye(3)
I_minus_C = I - C
d_demand = np.array([500, 800, 600])

print("--- Custom Solver Output ---")
x_econ_custom = custom_gaussian_elimination(I_minus_C, d_demand)

print("\n--- NumPy Solver Output ---")
x_econ_numpy = np.linalg.solve(I_minus_C, d_demand)
print(f"Total Production Required (in millions): {np.round(x_econ_numpy, 1)}")

# CONCLUSION:
# To sustain both the internal supply chain of the closed economy and the 
# external market demand, the total production must be roughly 1484.5 million 
# in Energy, 1630.7 million in Manufacturing, and 1193.3 million in Services.


# ==============================================================================
# PROBLEM 4: Kirchhoff’s Circuit Laws
# ==============================================================================
# THOUGHT PROCESS & MATHEMATICAL SETUP:
# I must account for missing variables by placing zeros in the matrix to 
# maintain the 4x4 shape.
# Loop 1: 10*I1 -  2*I2 -  3*I3 +  0*I4 =  12
# Loop 2: -2*I1 + 15*I2 +  0*I3 -  4*I4 =   5
# Loop 3: -3*I1 +  0*I2 + 12*I3 -  5*I4 =   0
# Loop 4:  0*I1 -  4*I2 -  5*I3 + 20*I4 = -10

print("\n### PROBLEM 4 OUTPUT ###")
R_matrix = np.array([
    [10, -2, -3,  0],
    [-2, 15,  0, -4],
    [-3,  0, 12, -5],
    [ 0, -4, -5, 20]
])
V_vector = np.array([12, 5, 0, -10])

print("--- Custom Solver Output ---")
I_custom = custom_gaussian_elimination(R_matrix, V_vector)

print("\n--- NumPy Solver Output ---")
I_numpy = np.linalg.solve(R_matrix, V_vector)
print(f"Loop Currents (Amperes): {np.round(I_numpy, 2)}")

# CONCLUSION:
# The negative value for I4 (-0.34A) indicates that the physical current in 
# loop 4 is actually flowing in the opposite direction of the engineer's 
# initial schematic assumption.


# ==============================================================================
# PROBLEM 5: Aerospace Trajectory Fitting
# ==============================================================================
# THOUGHT PROCESS & MATHEMATICAL SETUP:
# We are fitting a 4th-degree polynomial: y = a + b*x + c*x^2 + d*x^3 + e*x^4.
# We substitute the given (x, y) pairs into the equation. The powers of x 
# will form the columns of our 5x5 Vandermonde matrix.
# For example, x = -2: a(-2)^0 + b(-2)^1 + c(-2)^2 + d(-2)^3 + e(-2)^4 = 59
# We use list comprehension to dynamically generate these rows.

print("\n### PROBLEM 5 OUTPUT ###")
x_vals = [-2, -1, 1, 2, 3]
V_matrix = np.array([[x**0, x**1, x**2, x**3, x**4] for x in x_vals])
y_vector = np.array([59, 17, 5, 11, 49])

print("--- Custom Solver Output ---")
coeffs_custom = custom_gaussian_elimination(V_matrix, y_vector)

print("\n--- NumPy Solver Output ---")
coeffs_numpy = np.linalg.solve(V_matrix, y_vector)
print(f"Polynomial Coefficients [a, b, c, d, e]: {np.round(coeffs_numpy)}")

# CONCLUSION:
# The solved coefficients mean the exact mathematical model of the drone's flight 
# path can be represented by the function y = 7 - 4x + 3x^2 - 2x^3 + x^4.


### PROBLEM 1 OUTPUT ###
--- Custom Solver Output ---
Initial Augmented Matrix:
[[  2.   1.   1.  36.]
 [ -1.   2.  -1. -11.]
 [  3.  -1.   2.  47.]]
------------------------------
Matrix after zeroing below pivot in column 0:
[[ 1.   -0.33  0.67 15.67]
 [ 0.    1.67 -0.33  4.67]
 [ 0.    1.67 -0.33  4.67]]
------------------------------
Matrix after zeroing below pivot in column 1:
[[ 1.   -0.33  0.67 15.67]
 [ 0.    1.   -0.2   2.8 ]
 [ 0.    0.    0.    0.  ]]
------------------------------
Matrix after zeroing below pivot in column 2:
[[ 1.   -0.33  0.67 15.67]
 [ 0.    1.   -0.2   2.8 ]
 [ 0.    0.    1.   48.  ]]
------------------------------

--- NumPy Solver Output ---
Decrypted Message Packets (Custom): [-12.  12.  48.]
Decrypted Message Packets (NumPy): [-12.  12.  48.]

### PROBLEM 2 OUTPUT ###
--- Custom Solver Output ---
Initial Augmented Matrix:
[[ 30.  20.  50.  10. 145.]
 [ 40.  50.  20.  30. 210.]
 [ 10.  30.  20.  40. 115.]
 [ 20.  10.  40.  50. 170.]]
-------------